export const words = [
  // Animals
  { word: 'elephant', category: 'animals' },
  { word: 'penguin', category: 'animals' },
  { word: 'giraffe', category: 'animals' },
  { word: 'kangaroo', category: 'animals' },
  { word: 'octopus', category: 'animals' },
  { word: 'butterfly', category: 'animals' },
  { word: 'dolphin', category: 'animals' },
  { word: 'squirrel', category: 'animals' },
  { word: 'hamster', category: 'animals' },
  { word: 'crocodile', category: 'animals' },
  { word: 'flamingo', category: 'animals' },
  { word: 'hedgehog', category: 'animals' },
  { word: 'leopard', category: 'animals' },
  { word: 'ostrich', category: 'animals' },
  { word: 'peacock', category: 'animals' },
  { word: 'platypus', category: 'animals' },

  // Objects
  { word: 'bicycle', category: 'objects' },
  { word: 'telescope', category: 'objects' },
  { word: 'guitar', category: 'objects' },
  { word: 'computer', category: 'objects' },
  { word: 'microscope', category: 'objects' },
  { word: 'umbrella', category: 'objects' },
  { word: 'backpack', category: 'objects' },
  { word: 'flashlight', category: 'objects' },
  { word: 'keyboard', category: 'objects' },
  { word: 'sunglasses', category: 'objects' },
  { word: 'camera', category: 'objects' },
  { word: 'headphones', category: 'objects' },
  { word: 'suitcase', category: 'objects' },
  { word: 'toaster', category: 'objects' },
  { word: 'watch', category: 'objects' },
  { word: 'envelope', category: 'objects' },

  // Food
  { word: 'pizza', category: 'food' },
  { word: 'hamburger', category: 'food' },
  { word: 'spaghetti', category: 'food' },
  { word: 'sushi', category: 'food' },
  { word: 'pancake', category: 'food' },
  { word: 'ice cream', category: 'food' },
  { word: 'broccoli', category: 'food' },
  { word: 'pineapple', category: 'food' },
  { word: 'watermelon', category: 'food' },
  { word: 'croissant', category: 'food' },
  { word: 'burrito', category: 'food' },
  { word: 'cupcake', category: 'food' },
  { word: 'donut', category: 'food' },
  { word: 'mushroom', category: 'food' },
  { word: 'sandwich', category: 'food' },
  { word: 'taco', category: 'food' },

  // Nature
  { word: 'mountain', category: 'nature' },
  { word: 'sunflower', category: 'nature' },
  { word: 'waterfall', category: 'nature' },
  { word: 'rainbow', category: 'nature' },
  { word: 'volcano', category: 'nature' },
  { word: 'lightning', category: 'nature' },
  { word: 'cactus', category: 'nature' },
  { word: 'hurricane', category: 'nature' },
  { word: 'glacier', category: 'nature' },
  { word: 'forest', category: 'nature' },
  { word: 'desert', category: 'nature' },
  { word: 'island', category: 'nature' },
  { word: 'ocean', category: 'nature' },
  { word: 'canyon', category: 'nature' },
  { word: 'eclipse', category: 'nature' },
  { word: 'thunderstorm', category: 'nature' },

  // Jobs/Activities
  { word: 'astronaut', category: 'jobs' },
  { word: 'firefighter', category: 'jobs' },
  { word: 'dentist', category: 'jobs' },
  { word: 'scientist', category: 'jobs' },
  { word: 'detective', category: 'jobs' },
  { word: 'swimming', category: 'activities' },
  { word: 'painting', category: 'activities' },
  { word: 'dancing', category: 'activities' },
  { word: 'cooking', category: 'activities' },
  { word: 'fishing', category: 'activities' },
  { word: 'climbing', category: 'activities' },
  { word: 'cycling', category: 'activities' },
  { word: 'karate', category: 'activities' },
  { word: 'gardening', category: 'activities' },
  { word: 'reading', category: 'activities' },
  { word: 'skating', category: 'activities' },
  
  // Phrases / Compound Words
  { word: 'ice cream cone', category: 'food' },
  { word: 'hot air balloon', category: 'objects' },
  { word: 'golden gate bridge', category: 'nature' },
  { word: 'statue of liberty', category: 'objects' },
  { word: 'roller coaster', category: 'objects' },
  { word: 'swimming pool', category: 'objects' },
  { word: 'fire truck', category: 'objects' },
  { word: 'police station', category: 'objects' },
  { word: 'birthday cake', category: 'food' },
  { word: 'christmas tree', category: 'nature' }
];

export function getWordOptions(n: number): string[] {
  const shuffled = [...words].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, n).map(w => w.word);
}
